### PR TITLE
Iso

### PR DESCRIPTION
**Pull request by epmoyer**
Added a "Format:" section to the settings, with two new checkbox options:
world-clock_options
(Hmm, looking at it now the obsessive-compulsive in me says we should remove the period at the end of "Display times in system default format.", I will fix that after creating this PR.)

With both options unchecked, times now look like this:
world-clock_iso_and_no_microseconds

You may want to reject the `in-project = true` setting in `poetry.toml`

The `alfred-pyflow = ">=0.3.3"` change in `pyproject.toml` was necessary to make poetry 1.3.1 happy (it was complaining about the setting `"latest"`)

Cheers!

### CODE REVIEW

**Comment by fedecalendino** [comment]
Excellent thanks!

How would you feel about doing it as a dropdown with multiple string formats instead?

* Default format (the one that I made).
* ISO format
* ISO format with microseconds


Then instead of an `if` we can just pull the formatting string from the settings and apply directly to the date.

**Comment by epmoyer** [comment]
The reason for splitting it into two checkboxes was to separate ISO formatting from display formatting.  Today (before this PR) the display format is the system default and the copy format is ISO (with microseconds).  So there may be existing users out there that are "already accustomed to" seeing the display format in their system default, but who may still wish that the copy format excluded microseconds.  Having two boxes allows them to accomplish that (and I chose the defaults so that the default is the pre-PR behavior).

I think that having a single 3-option drop-down would only make sense if the display format and the copy format were unified (i.e. implemented to always match each other), but that deviates from the current behavior (which displays as system default and copies as ISO).  Personally, I'd be fine displaying and copying in ISO without microseconds (which is how I have my instance set anyway), but most project maintainers try to not "break" existing functionality, so it's up to you whether you'd want to "take away" the existing ability to display in system default but copy as ISO.

That said, my personal feeling is that displaying one format and copying another makes for a confusing UI, and I also feel like anyone who wants the copy format to be ISO is a person who already lives and breathes ISO, and those people would all probably rather see ISO as the display format anyway.  So ignoring past history I do feel like unifying the display/copy formats and having a single drop down is a "better" UI, so long as you are OK with "taking away" a current capability.

**Comment by fedecalendino** [comment]
> That said, my personal feeling is that displaying one format and copying another makes for a confusing UI.

I completely agree with this, having different copies might make it a bit tricky. So, we could do something like this:


1. Add a dropdown with 3 options (current format, ISO and ISO with ms.).
2. Make it that just pressing `enter` it copies the value as displayed in the item.
3. Alternatively, we could add `cmd+enter` and `alt+enter` options to copy the iso date regardless of the selected format. It can be done like this:


```python
  item = workflow.new_item(
    ...,
    arg=display_time,
    ...,
  )

  item.set_alt_mod(
      subtitle="Copy ISO format",
      arg=now.isoformat(),
  )

  item.set_cmd_mod(
      subtitle="Copy ISO format",
      arg=now.isoformat(),
  )
```

Then the second action in the workflow will pick that `arg` up and add it to your clipboard.

CleanShot 2022-12-31 at 18 40 14@2x


I'll be about for a while but as soon as I can I'll review the PR properly!


Cheers and happy new year,
Fede :)

**Comment by epmoyer** [comment]
Sounds good to me!

Pushing an update now.  The format selection is now a dropdown like this:
clock_dropdown1
clock_dropdown2

And alt/cmd can be held to force ISO with or without microseconds:
- `alt`
   - clock_alt_key
- `cmd`
   - clock_command_key

Earlier you said:
> Then instead of an if we can just pull the formatting string from the settings and apply directly to the date.

But instead I had the settings dropdown "return" a mode string (e.g. `FORMAT_ISO8601_WITH_MICROSECONDS`) that I do an if/elif/else "case" statement on.  That's because for the default format you were already doing `os.getenv()` to use formats set by the env, so that one had to be a "case" statement anyway, so I just made all 3 cases rather than embed `strftime` format strings in the settings dropdown data.

**Comment by epmoyer** [comment]
I've updated the README for the new options.  All done for now.

**Comment by fedecalendino** [comment]
@epmoyer that is amazing! i'll review it as soon as I can and make the release.

Thank you so much, really appreciate it!

Fede

**Review by fedecalendino — APPROVED** [review]

**Comment by fedecalendino** [comment]
Hi again @epmoyer!

The PR has been merged, thanks a lot for it.

I did after after some refactoring to my old code since it was getting a bit complicated and took the chance to move your formatters to another file and then fetching the correct one from the main thread.

Your changes should be available in the `v1.9.0` in the releases section of this repo.

Cheers, Fede.

**Pull request merged**
